eureka:
    client:
        register-with-eureka: false
server:
    port: 8222
spring:
    application:
        name: gateway
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
            routes:
                - id: students
                  uri: http://localhost:8090
                  predicates:
                      - Path=/api/v1/students/**
                - id: schools
                  uri: http://localhost:8070
                  predicates:
                      - Path=/api/v1/schools/**
                - id: thirdparties
                  uri: http://localhost:8071
                  predicates:
                      - Path=/thirdparties/**
                #   - Path=/swagger-ui/**
                - id: issues
                  uri: http://localhost:8091
                  predicates:
                      - Path=/issues/**
                #       - Path=/swagger-ui/**
management:
    tracing:
        sampling:
            probability: 1.0
