eureka:
    instance:
        hostname: localhost
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
server:
    port: 8091
spring:
    application:
        name: issues
    data:
        mongodb:
            uri: "mongodb+srv://optimus:optimus123@cluster0.d8cot9o.mongodb.net/issues"

management:
    tracing:
        sampling:
            probability: 1.0
