server:
    port: 8071
spring:
    data:
        mongodb:
            uri: "mongodb+srv://optimus:optimus123@cluster0.d8cot9o.mongodb.net/third_parties"

application:
    config:
        issues-url: http://localhost:8222/issues/external-sources
        authorization-url: http://localhost:8222/api/v1/auth

management:
    tracing:
        sampling:
            probability: 1.0
